model_config:
  model: UNET3D
  classes: 4
  opt: sgd
  inChannels: 2
  lr: 1e-3
  terminal_show_freq: 50 # how many iterations for terminal display
  log_dir: '../runs/'
  nEpochs: 5
  inModalities: 2
  cuda: False
