model_config:
  model: UNET3D
  classes: 4
  opt: sgd
  inChannels: 4
  lr: 1e-2
  terminal_show_freq: 50 # how many iterations for terminal display
  log_dir: '../runs/'
  nEpochs: 100
  inModalities: 4
  cuda: False
