COVIDNET: 'COVIDNet'
DENSENET3: 'Densenet3D'
DENSEVOXELNET: 'DenseVoxelNet'
HIGHRESNET3D: 'HighResNet3D'
HYPERDENSENET: 'HyperDensenet'
RESNET3DVAE: 'ResNet3D_VAE'
RESNET3DMEDNET: 'ResNet3DMedNet'
SKIPDENSENET3D: 'SkipDenseNet3D'
UNET2D: 'Unet2D'
UNET3D: 'Unet3D'
VNET: 'Vnet'

COVID_CT: 'covid_ct_dataset'
COVIDx: 'covid_x_dataset'
iseg2017: 'iseg_2017'
iseg2019: 'iseg_2019'
ixi: 'ixi'
miccai2019: 'MICCAI_2019_pathology_challenge'
brats2018: 'MICCAI_BraTS_2018_Data_Training'
brats2019: 'MICCAI_BraTS_2018_Data_Training'
brats2020: 'MICCAI_BraTS_2018_Data_Training'
mrbrains: 'mrbrains_2018'