
batchSz: 2
dim: [32,32,32]
nEpochs: 5
classes: 4
samples_train: 10
samples_val: 10
inChannels: 2
inModalities: 2
threshold: 0.0001  # threshhold for non-empty sub volume sampling
terminal_show_freq: 50 # iterations for terminal display
augmentation: true # whether to use 3D data augmentations
normalization: 'full_volume_mean' #('max_min', 'full_volume_mean', 'brats', 'max', 'mean')
fold_id: 1
split: 0.8 # how to split train and val data
lr: 1e-3
fold_lr: 1
cuda: false
loadData: false
resume: '' # define your checkpoint here
opt: sgd #('sgd', 'adam', 'rmsprop')
log_dir: '../runs/'
# TODO
pretrained: false # search for pretrained models with the same input modalities


